sudo: required
services:
  -docker

before_install:
  - docker build -t kghussein14/multi_docker -f Dockerfile.dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kghussein14/multi_docker npm run test -- --coverage

after_success:
  - docker build -t kghussein/multi-client ./client
  - docker build -t kghussein/multi-nginx ./nginx
  - docker build -t kghussein/multi-server ./server
  - docker build -t kghussein/multi-worker ./worker
  #To log in to docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kghussein/multi-client
  - docker push kghussein/multi-nginx
  - docker push kghussein/multi-server
  - docker push kghussein/multi-worker
Deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-795032617159"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

